# ===================== config.yaml =====================
entrenamiento:
  usar_validacion_cruzada: false   # true → CV | false → simple
  num_folds: 5
  batch_size: 16
  num_epochs: 15
  learning_rate: 2e-5
  weight_decay: 0.01
  patience: 5
  min_delta: 0.001

modelo:
  tipo: "xlmrgalem"
  path: 'IIC/XLM-R_Galen'
  max_len: 512

datos:
  ruta_csv: 'C:\Users\jesus\OneDrive - Universidad de Málaga\Cuarto\TFG\Multiples_neoplasias_solo_resumenes_selection\textos_cortos_filtrados.csv'
  columna_texto: "TEXTO"
  columna_etiqueta: "MULTIPLES"
  test_size: 0.2
  random_state: 42

salida:
  carpeta_resultados: 'C:\Users\jesus\OneDrive - Universidad de Málaga\Cuarto\TFG\NeoplasiaClassifier-ES\output\xlm_r_galen\xlm_r_galen_2'
