modelo:
  ruta_modelo: "../models/binario/galen_1"
  ruta_tokenizer: "../models/binario/galen_1"
  max_length: 512

cascade:
  ruta_mama_model: "../models/mama/best_model"
  ruta_mama_labels: "../models/mama"
  ruta_resto_model: "../models/resto/best_model"
  ruta_resto_labels: "../models/resto"
  umbral_mama: 0.5
  umbral_resto: 0.2

api:
  titulo: "Clasificador de Neoplasias"
  version: "1.0"